# fly.toml file for deploying Django on Fly.io
app = "swiss-watches-backend"  # Change this to your actual app name

[build]
  working_directory = "Backend/Hello"  # Set correct subfolder path

[deploy]
  release_command = "python manage.py migrate"  # Run migrations before deploy

[env]
  PORT = "8080"
  DATABASE_URL = "postgresql://neondb_owner:npg_tJHc7Oxfrl2E@ep-dark-glitter-a5hbruy9-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"  # Use Fly.io secrets instead of hardcoding this

[processes]
  web = "gunicorn Hello.wsgi --bind 0.0.0.0:8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80  # HTTP

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443  # HTTPS

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"

